name: Test dotnet new vrisingmod

on:
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.x', '8.x']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install, Create, and Build .NET Template
      run: |
        dotnet new install vrising.modtemplate
        dotnet new vrisingmod -n FullTemplateTest --use-vcf --use-bloodstone
        cd FullTemplateTest
        dotnet build -warnaserror
